[package]
name = "naslr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
naslr-sys = { version = "0.1.0", path = "naslr-sys" }
thiserror = "1.0.50"

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"
